import { Router } from "express";

import adminRouter from "./admin";
import clientRouter from "./client";
import clientAuthRouter from "./clientAuth";
import campRouter from "./camp";
import posRouter from "./pos";
import posDeviceCodeRouter from "./posDeviceCodeByAdmin";
import posDeviceCodeHistoryRouter from "./posDeviceCodeByClient";
import internetPackageRouter from "./internetPackage";
import posAuthRouter from "./posAuth";
import adminCoordinatorRouter from "./adminCoordinator";
import adminAccountantRouter from "./adminAccountant";
import internetPackageClientRouter from "./internetPackageClient";
import userRouter from "./user";
import countriesRouter from "./countries";
import nationalTypeRouter from "./nationalType";
import campLocationRouter from "./camp-location";
import clientCoordinatorRouter from "./clientCoordinator";
import clientAccountantRouter from "./clientAccountant";
import adminInvestorsRouter from "./adminInvestors";
import clientInvestorsRouter from "./clientInvestors";
import coordinatorAuthRouter from "./coordinatorAuth";
import accountantAuthRouter from "./accountantAuth";
import investorsAuthRouter from "./investorsAuth";
import plantManagerRouter from "./plantManager";
import plantManagerAuthRouter from "./plantManagerAuth";

const router = Router();
router.use("/api/admin", adminRouter);
router.use("/api/admin", clientRouter);
router.use("/api/client-admin", clientAuthRouter);
router.use("/api/client-admin", campRouter);
router.use("/api/client-admin", posRouter);
router.use("/api/pos", posAuthRouter);
router.use("/api/admin", posDeviceCodeRouter);
router.use("/api/client-admin", posDeviceCodeHistoryRouter);
router.use("/api/admin", internetPackageRouter);
router.use("/api/pos", posAuthRouter);
router.use("/api/admin", adminCoordinatorRouter);
router.use("/api/admin", adminAccountantRouter);
router.use("/api/client-admin", internetPackageClientRouter);
router.use("/api/users", userRouter);
router.use("/api/admin", countriesRouter);
router.use("/api/admin", nationalTypeRouter);
router.use("/api/camp", campLocationRouter);
router.use("/api/client-admin", clientCoordinatorRouter);
router.use("/api/client-admin", clientAccountantRouter);
router.use("/api/admin", adminInvestorsRouter);
router.use("/api/client-admin", clientInvestorsRouter);
router.use("/api/coordinator", coordinatorAuthRouter);
router.use("/api/accountant", accountantAuthRouter);
router.use("/api/investor", investorsAuthRouter);
router.use("/api/admin", plantManagerRouter);
router.use("/api/plant-manager", plantManagerAuthRouter);

export default router;
